language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.2.2
  - ruby-head
  - jruby
  - rbx-2

jdk:
  - oraclejdk7
  - openjdk7

env: CI="travis" JRUBY_OPTS="--2.0 --server -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -J-Xms512m -J-Xmx1024m"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby

env: CI="travis"
